# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        mkdir output && cp target/*.jar output
      
    - name: Caching
      uses: actions/cache@v2
      with: 
        path: ~/.m2
        key: ${{runner.os}}-m2-${{hashFiles('**/pom.xml')}}
        restore-keys: ${{runner.os}}-m2
    
    - name: Persist workflow data as artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: guesstheword-snapshot
        path: output